
server:
  port: 9090

spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework_manager?characterEncoding=utf-8&useSSL=false&useLocalSessionState=true&serverTimezone=Asia/Shanghai
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 20                                         # 最大连接数
      max-wait-millis: 1000                                 # 等待连接获取的最大超时时间



#自定义的消息发布starter模块配置
message:
  publish:
    retry-flag: false
    retry: 3
    max-spin-time: 1000

#rocketmq配置
rocketmq:
  name-server: 106.53.103.199:9876
  producer:
    group: default-group
  consumer:
    group: default-group
